### ISSUE TITLE
Crates are interpreted as their own sectors, splitting the containing sector

### ISSUE THREAD

**Issue by bgaesslein** [monsharen/build-engine-unity#6]
![image](https://github.com/monsharen/build-engine-unity/assets/86594273/4f47b6cd-cd0c-4624-b2bb-dbba76a460c7)

**Comment by thomas-rosenquist** [comment]
This is an interesting take on this. I believed these to be actual sectors, faking boxes, but do you mean that they are a special case?

**Comment by bgaesslein** [comment]
I tried skipping the rendering of all the box-sectors and it worked but the ceiling still isn't complete so I guess it's not that. I get how the boxes work, they're a sector that has four walls below the "floor" and the "ceiling" is blended into the room sector's ceiling. Interestingly the containing sector also has four walls for the insides of the boxes even though these should never be seen.

It is peculiar that the ceiling holes usually correlate with such thresholds/overlapping sectors. Needs further research on why this happens.

**Comment by bgaesslein** [comment]
This is the ceiling without the boxes. Interestingly, part of the ceiling is simply not textured, including that one part isn't covered by the box "ceiling". There's still a good chunk missing tho.
Is there a way to see all the triangles that are part of the ceiling thingy? It looks like there's one ceiling-triangle that should be textured but isn't.

![image](https://github.com/monsharen/build-engine-unity/assets/86594273/ffd54a73-797d-4fe0-b36f-0fa0880bd84a)

**Comment by thomas-rosenquist** [comment]
I've seen missing triangles elsewhere, and possibly triangles where there should be no triangle. Could they all be accidentally shifted +1 somewhere? Not that I necessarily think that's it, because that should probably lead to much more messy stuff.  More likely an issue with the triangle algo for sectors as you're alluding to

**Comment by bgaesslein** [comment]
This is the ceiling mesh, the lines seem to sometimes stop when they hit another ceiling mesh, you can see the outline of two of the boxes there

![image](https://github.com/monsharen/build-engine-unity/assets/86594273/ee0f5aa3-72a4-4bcd-aa69-d7f146477a75)

**Comment by thomas-rosenquist** [comment]
Thought: Have you seen this on floors anywhere, or is it only ceilings?

**Comment by thomas-rosenquist** [comment]
Here's something. When we construct sector floor/ceiling we use the sectorWalls to get the edges. We use this method to find all walls. Can't work out in my head whether we get all points here, or if we actually miss out on 1 wall

var sectorWalls = map.Walls.Skip(sector.FirstWallIndex).Take(sector.NumWalls);

**Comment by bgaesslein** [comment]
I've been wondering, the code for creating ceilings and floors is exactly the same except for two lines that reverse the vertices and uv lists. This could probably be refactored to save on some code duplication but that's besidee the point, which is: I haven't seen floors with "holes" in them. And commenting out the reverse() functions actually leads to a flawlessly filled ceiling here - but only when viewed from above.

**Comment by thomas-rosenquist** [comment]
It is a copy and exactly that, I was thinking I'd refactor it later so please go ahead and do anything you feel would improve it. 

That said, I agree that the reverse function is super dodgy. I figured it was a way to flip the normals, but kind of suspected it wouldn't be that easy. I think you found it's not the correct way to do it.

**Comment by thomas-rosenquist** [comment]
I am wondering if all of these reverse calls is really a sign of something worse: 
https://github.com/monsharen/build-engine-unity/issues/10

I probably started making something upside down somewhere, and then felt I had to reverse everything down the line

**Comment by bgaesslein** [comment]
PS: yeah, looks pretty good. Shall I commit directly to main or do you prefer a pull request? :)

**Comment by thomas-rosenquist** [comment]
go for whatever is easiest

**Comment by bgaesslein** [comment]
Made a pull request, gotta have some code review haha.

Also is it me or do ceilings and floors often have more triangles than the need? Could be something to optimize, maybe? Not sure what the impact is.
